---
kind: pipeline
type: docker
name: default
globals:
  - &docker_creds
    username:
      from_secret: DOCKER_USER
    password:
      from_secret: DOCKER_PASS
steps:
  # - name: prepare
  #   image: busybox
  #   commands:
  #     - mkdir -p /cache/${DRONE_REPO}/docker
  #   volumes:
  #     - name: cache
  #       path: /cache
  - name: build
    image: plugins/docker
    settings:
      registry: docker-registry.vicoders.com
      repo: docker-registry.vicoders.com/docker-laravel-remote-image
      tags:
        - ${DRONE_COMMIT_BRANCH}
      create_repository: true
      use_cache: true
      <<: *docker_creds
    # volumes:
    #   - name: docker
    #     path: /var/lib/docker
  # - name: deploy
  #   image: appleboy/drone-ssh
  #   settings:
  #     host:
  #       from_secret: SERVER_IP
  #     ssh_key:
  #       from_secret: SERVER_SSH_KEY
  #     port: 1080
  #     script:
  #       - docker pull docker-registry.vicoders.com/webpress_vn:${DRONE_COMMIT_BRANCH}
  #       - docker service update --image docker-registry.vicoders.com/webpress_vn:${DRONE_COMMIT_BRANCH} --force $SERVICE_NAME
  #       - docker system prune -f
# volumes:
#   - name: cache
#     host:
#       path: /var/cache
#   - name: docker
#     host:
#       path: /var/cache/${DRONE_REPO}/docker

trigger:
  branch:
    - php74
    - php73
    - php72
